yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug>/', views.group_post, name='group_list'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Group(models.Model):
    title = models.CharField(verbose_name='Название', max_length=200)
    slug = models.SlugField(verbose_name='Слаг', unique=True)
    description = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст поста', max_length=3000)
    pub_date = models.DateTimeField(verbose_name='Дата публикации',
                                    auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               verbose_name='Автор',
                               related_name='posts_author')
    group = models.ForeignKey(Group, on_delete=models.SET_NULL,
                              verbose_name='Группа',
                              related_name="posts_group", blank=True,
                              null=True)

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Group


def index(request):
    posts = Post.objects.all()[:10]
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


def group_post(request, slug):
    NUMBER_OF_POSTS = 10
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).all()[:NUMBER_OF_POSTS]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
  <head>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <meta charset="utf-8">
    <title>{% block title %}title{% endblock %}</title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
        контент не подвезли :(
      {% endblock %}
    </main>
    <footer class="page-footer font-small blue border-top">
      {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
<p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
{% load static %}
<!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <!-- В дальнейшем тут будет создано полноценное меню -->
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30"
           class="d-inline-block align-top" alt="">
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
      <span style="color:red">Ya</span>tube
    </a>
  </div>
</nav>

yatube/templates/includes/post_card.html
<ul>
  <li>
    Автор: {{ post.author.get_full_name }}
  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
</ul>
<p>{{ post.text|linebreaksbr }}</p>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block content %}
<head>
  <title>{% block title %}{{ group.title }}{% endblock %}</title>
</head>
<div class="container">
  <h1>{{ group.title }}</h1>
  <p>{{group.description}}</p>
  {% for post in posts %}
  <article>
    {% include 'includes/post_card.html' %}
  </article>
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  <!-- под последним постом нет линии -->
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block content %}
<head>
  <title>{% block title %}Последние обновления на сайте{% endblock %}</title>
</head>
<div class="container">
  <h1>Последние обновления на сайте</h1>
  {% for post in posts %}
  <article>
    {% include 'includes/post_card.html' %}>
    {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.title %}">все записи
        группы {{ post.group.title }}</a>
    {% endif %}
  </article>
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
</div>
{% endblock %}